# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Github Actions Runner
version: "3"
slug: gha-runner
description: Self-hosted Github Actions Runner to run GHA jobs on
url: "https://github.com/AngellusMortis/ha-addons/tree/master/gha-runner"
arch:
  - armv7
  - aarch64
  - amd64
options:
  token: null
  repo: null
  name: ha-runner
  labels: linux,ha
  workdir: /share/gha-runner
schema:
  token: password
  repo: url
  name: str
  labels: str
  workdir: str
map:
  - "share:rw"
